### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by JiriTrecak** [eonist/Element#4]
Hey! 

First, great job guys - seems like A LOT of work has been put into it and it is definitely something that is sorely missing on OSX.

Now, as for the issue - Element is currently missing description about how to implement it in the project itself - and it does not seem easy on the first look - is there possibility you could extend readme to have this described more properly?

Also, have you thought about using CocoaPods? That would help immensely and definitely would allow more people to use the project.

Thank you very much!
Sincerely
JT

**Comment by eonist** [comment]
Thanks. Just 1 guy on this project. In my spare time. Currently i'm implementing Core animation. Adding physics to the ScrollList etc. sneak peak: https://github.com/stylekit/stylekit.github.io/blob/master/_posts/_2016-02-13-The-list.md  and general Core anim research: https://github.com/stylekit/stylekit.github.io/blob/master/_posts/_2016-02-20-Core-animation.md

I'm not sure which model i will use to distribute it. Cocoapods, cassette, carthage etc. I will have to research which solution fits the project as it has quite a a lot of utility classes. No external dependencies. 

I made this framework in the context of what I needed. I need to do more research into how general Xcode frameworks works best for the many. Then apply it to the project. 

**So to sum up whats left before package distribution:**
1. Implement core anim (CVDisplayLink FPS anim) 
2. finish the components (Just a few left)
3. clean up the comments etc (just aesthetics for now)
4. clean up the file folders (remove deprecated files)
5. add the OSX Mavricks css files (done, Yosemite styles will be done later 1-2 days of work)

Then I will do the research into how to best distribute it to the many. It works in Xcode playground as well so I have to keep that in mind when choosing distribution package. I read somewhere that someone got cocoapods working with playground.

So how long will this take? Not too long. The fps animation seems straight forward to implement. The other stuff is basically ready to go. anywhere from 1-2 weeks. Then a couple of days to convert the project into something distributable. And clean up descriptions and install guides etc. 

**Here is whats coming in the near future**: https://github.com/eonist/Element/wiki/Roadmap

**Comment by eonist** [comment]
Here is whats coming in the near future: https://github.com/eonist/Element/wiki/Roadmap

**Comment by eonist** [comment]
Just finished the Animation-engine for the framework: http://stylekit.org/blog/2016/03/08/Rubber-band-slider-list/  Now full steam ahead with the other stuff ;)

**Comment by eonist** [comment]
- Finished OSX 10.11 El cap styles.
- Live editing of styles while the app is running
- Support for Translucent windows

The project is complete for my use. It will get better once i make the first full fledged app with it. Im unsure about adding cocoa pod, carthage etc. Im researching which is the best approach: [here](https://github.com/eonist/research/wiki/XCode-framework)  Any input is welcomed. 

Here is how you can install Element: https://github.com/eonist/Element/wiki/tutorials

**Comment by eonist** [comment]
@JiriTrecak Element now has Swift package manager support 👍
