### ISSUE TITLE
demo app?

### ISSUE THREAD

**Issue by HamGuy** [eonist/Element#6]
Could your share the demo app in readme document?

**Comment by eonist** [comment]
Yepp, its this one: https://github.com/eonist/GitSyncOSX

Its beeing activly developed, currently working on a more performant List component.

**Comment by eonist** [comment]
Here is a simpler demo app: http://stylekit.org/blog/2016/03/09/Demo-app/

<img width="580" alt="img" src="https://dl.dropboxusercontent.com/u/2559476/Screen%20Shot%202017-01-06%20at%2014.04.39.png">

The .css examples are still available. Unfortunately the example .swift code is not available anymore. Unless you roll back git history to march of last year.

**Comment by HamGuy** [comment]
Wow, many thanks

**Comment by eonist** [comment]
Source code for the example app: https://github.com/stylekit/stash
