### ISSUE TITLE
Retrocompatibility

### ISSUE THREAD

**Issue by melMass** [eonist/Element#9]
Hello,

I'm mainly targeting older mac versions (as far as Marverick).
Is there a way to make Element compatible with these ? If not what would be the oldest supported os, El Captain ?

Thanks

**Comment by eonist** [comment]
Hey, Thanks for your interest in Element!

Element was built with Mavericks css last year. https://github.com/stylekit/mavericks

Pardon the TitleBar buttons. Close,Min,Max. The correct gradient styles are available in the above link.

**Comment by melMass** [comment]
Great news! I have to check how SPM really works then.
Does this apply to swift-utils aswell ?

Thanks for those by the way !

**edit**: So swift-utils it a dependency of Element. I did not get the SPM workflow right I think because it complains about 10.12 features missing

**Comment by eonist** [comment]
You are welcome. 

You can use Element without SPM. Download source for swift-utils. And build as .framework. then do the same for Element. 

As for backwards compatibility with functions. I am not sure that I use that many El cap only api's. In any case you can probably exclude these calls.

**Comment by melMass** [comment]
Thanks.
To make .frameworks out of them I use `swift package generate-xcodeproj`and the open and build right ?

**Comment by melMass** [comment]
When doing the simple `swift build`on Element (on El Captain) I have the following error:

`/dev/mac/Element/src/Element/ui/list/concrete/composite/FastList.swift:17:13: error: use of undeclared type 'Dir'
    var dir:Dir = .ver//new`

followed by a bunch of errors related to this missing Dir class

**Comment by eonist** [comment]
Experimental code. I'm revamping Element to be Protocol oriented 😁 https://github.com/eonist/swift-utils/blob/master/Sources/Utils/misc/layout/direction/Dir.swift

Make sure you build .framework for swift-utils first. If you want to use the latest dev stuff. 

More stable versions can be found under releases:

https://github.com/eonist/Element/releases   
https://github.com/eonist/swift-utils/releases

Sorry for the inconvenience. I push directly on master to keep momentum up. Also scrambling to release the first Full fledged app built with Element. So that Element is more than academic. https://github.com/gitsync/GitSyncMac

**Comment by melMass** [comment]
Thanks for the time I'll try right away.
 
I did see your frequent master push 💃 
GitSync looks great. 
Just discovered your blog, precious tips in there thanks!

**Comment by eonist** [comment]
Thx. stylekit.org is my personal notebook. For even more experimental stuff check out the unreleased blog post section: https://github.com/stylekit/stylekit.github.io/tree/master/_posts/_temp 

The frequent master push is sort of bad. I will change this when GitSync for mac comes out. In its current incarnation the workflow for branches is too cumbersome. I except to be on track with this circa 1 of May. Also Element will be conducted in a more community friendly manor with more stable API's etc. At the moment it's the wild west to experiment fast. 

That being said. Element for mac is almost done. I will make it more POP friendly vs OOP as it is now. And then add FlexBox and make styles load faster on a background thread. 

The main focus of Element in the future will be for iOS. And then Mac and iOS will feed of each other. Morphing closer and closer until You can almost deploy apps for platforms with the same framework.

**Comment by eonist** [comment]
I Just tested Making app with .frameworks and it worked then I made an instruction about the process, long overdue.

https://github.com/eonist/Element/wiki/framework-instructions

**Comment by melMass** [comment]
I was doing exactly that (tried to install and reporting it as documentation), your faster! Thanks a lot

**Comment by eonist** [comment]
Thanks for the effort/thought. 

Feel free to ask any question. I would recommend trying to learn SPM. As it speeds up coding as you can see the src and build from framework at the same time. So if there is no change to framework then build time is zero. It could be possible without SPM as well. Although I never figured out how. If you wire up the targets right etc. Then possibly. I think it will work. I just don't have it clear in my head at the moment. If you figure it out please share.

**Comment by melMass** [comment]
@eonist For some reason I can't build Element on **El Capitan**. I'm trying to adopt the **SPM** way.
Here are my steps:
```bash
git clone https://github.com/eonist/Element.git
cd Element
swift package fetch
# Cloning https://github.com/eonist/swift-utils.git
# HEAD is now at d0a3f06e Remove carthage support badge
# Resolved version: 0.0.0-alpha.4

swift package generate-xcodeproj
#generated: ./Element.xcodeproj
open Element.xcodeproj
```
Then when I build I have the same error as before, `undeclared type Dir`, what is strange is that I do miss the `/misc/layout/direction/Dir.swift`file  😭

**Comment by eonist** [comment]
If you use SPM, you have to use releases. and then after you can pull in latest from master. Ill make a write up tonight.

**Comment by eonist** [comment]
Basically follow this http://stylekit.org/blog/2017/02/05/Xcode-and-spm/ for spm. No clone involved. I will make a video when I get home tonight.

**Comment by melMass** [comment]
Yes it worked !!
I did grasp the concept behind SPM a bit better now, and I love it's simplicity and scalability.

Thanks again
